import { LayoutDashboard, Box, ChartNoAxesCombined, BrainCircuit, FlaskConical, Wrench, Database, FileText, ChevronDown, ArrowUpRight, Activity, CircleHelp, Menu, X } from 'lucide-react';
import { useState } from 'react';
import { useBridge } from '../../store/bridgeStore';
import { dateLabel } from '../../utils/format';
const nav=[['overview','Overview',LayoutDashboard],['twin','Digital Twin',Box],['analytics','Analytics',ChartNoAxesCombined],['predictions','Predictions',BrainCircuit],['simulation','Simulation Lab',FlaskConical],['maintenance','Maintenance Planner',Wrench],['data','Data Explorer',Database],['reports','Reports',FileText]];
export default function Layout({children}) {
  const {page,navigate,state,playing}=useBridge(); const [open,setOpen]=useState(false);
  return <div className="app-shell"><aside className={`sidebar ${open?'sidebar-open':''}`}><a className="brand" href="#overview" aria-label="BridgeTwin AI home"><img src="/favicon.svg" alt=""/><div><strong>BridgeTwin<span> AI</span></strong><small>See Today. Predict Tomorrow.</small></div></a><div className="workspace-label">WORKSPACE <span>01</span></div><nav>{nav.map(([key,label,Icon],i)=><button key={key} className={`nav-item ${page===key?'active':''} ${i===6?'nav-divider':''}`} onClick={()=>{navigate(key);setOpen(false);}}><Icon size={18}/><span>{label}</span>{key==='twin'&&<em>3D</em>}</button>)}</nav><div className="sidebar-bottom"><div className="model-status"><BrainCircuit size={18}/><div><b>Hybrid intelligence</b><span>{state?.metadata.model_status==='Trained'?'Physics + machine learning':'Physics simulation'}</span></div></div><button className="methodology-link" onClick={()=>navigate('data')}><CircleHelp size={16}/>Data & methodology<ArrowUpRight size={14}/></button><div className="workspace-owner"><span>BT</span><div><b>Academic workspace</b><small>BridgeTwin AI · v1.0</small></div></div></div></aside>
    {open&&<button className="mobile-overlay" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}</button><span>Workspace</span><span className="slash">/</span><b>{nav.find(n=>n[0]===page)?.[1]||'Overview'}</b></div><div className="topbar-right"><span className={`live-status ${playing?'is-playing':''}`}><i/>{playing?'SIMULATED LIVE DATA':'SIMULATION READY'}</span><span className="header-date">{state?dateLabel(state):'Loading…'}</span><div className="avatar">PK</div></div></header>
      <div className="bridge-context"><div><span className="bridge-mini-icon"><Activity size={16}/></span><b>Mula River Bridge</b><span className="context-id">BT-PUNE-001</span></div><span className="fiction-label">Fictional demonstration asset <span>·</span> Pune, India</span></div>
      <main>{children}</main><footer>BridgeTwin AI is an academic decision-support prototype. Outputs do not replace certified structural inspection or engineering assessment.<span>SIMULATION-DRIVEN DIGITAL TWIN</span></footer>
    </div></div>;
}
