import { ResponsiveContainer, AreaChart, Area, LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, Cell, ScatterChart, Scatter, ReferenceLine } from 'recharts';
import { color, num } from '../../utils/format';
const axis = { tick: { fill: '#7c8996', fontSize: 12 }, axisLine: false, tickLine: false };
const tip = { contentStyle: { background: '#fff', border: '1px solid #e3e9ed', borderRadius: 10, fontSize: 13 }, formatter: (value, name) => [num(value, 2), name] };
export function TrendChart({ data, lines = [{ key: 'health_score', name: 'Health score', color: '#199c81' }], xKey = 'year', height = 240, domain = [0, 100], area = true }) {
  const Chart = area && lines.length === 1 ? AreaChart : LineChart;
  return <div className="chart-wrap" style={{ height }}><ResponsiveContainer width="100%" height="100%"><Chart data={data} margin={{ top: 12, right: 16, left: -18, bottom: 2 }}>
    <defs><linearGradient id="health-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22aa8b" stopOpacity={.19}/><stop offset="100%" stopColor="#22aa8b" stopOpacity={.01}/></linearGradient></defs>
    <CartesianGrid vertical={false} stroke="#edf1f4" strokeDasharray="3 4"/><XAxis dataKey={xKey} {...axis} minTickGap={30} tickFormatter={v => Number(v)%1 ? '' : v}/><YAxis domain={domain} {...axis}/><Tooltip {...tip}/>
    {lines.map(l => Chart === AreaChart ? <Area key={l.key} type="monotone" dataKey={l.key} name={l.name} stroke={l.color} fill="url(#health-fill)" strokeWidth={2.5} isAnimationActive={false}/> : <Line key={l.key} type="monotone" dataKey={l.key} name={l.name} stroke={l.color} strokeWidth={2.5} strokeDasharray={l.dashed ? '5 5' : undefined} dot={false} isAnimationActive={false}/>)}
    {lines.length > 1 && <Legend iconType="plainline" wrapperStyle={{ fontSize: 12, paddingTop: 12 }}/>}</Chart></ResponsiveContainer></div>;
}
export function ComponentChart({ components, height = 250 }) { return <div className="chart-wrap" style={{ height }}><ResponsiveContainer><BarChart data={components} margin={{ top: 12, right: 10, left: -25, bottom: 5 }}><CartesianGrid vertical={false} stroke="#edf1f4"/><XAxis dataKey="name" {...axis} tickFormatter={v => v.replace('Expansion joint', 'Joint').replace('Bearing group', 'Bearings').replace('Main deck', 'Deck')} interval={0} tick={{ fontSize: 11, fill: '#7c8996' }}/><YAxis domain={[0, 100]} {...axis}/><Tooltip {...tip}/><Bar dataKey="health_score" name="Current health" radius={[4, 4, 0, 0]} maxBarSize={38}>{components.map(c => <Cell key={c.component_id} fill={color(c.risk_level)}/>)}</Bar><Bar dataKey="predicted_health_5y" name="5-year estimate" fill="#d7e0e7" radius={[4,4,0,0]} maxBarSize={20}/></BarChart></ResponsiveContainer></div>; }
export function ScatterPlot({ data, xKey, xLabel, height = 240 }) { return <div className="chart-wrap" style={{ height }}><ResponsiveContainer><ScatterChart margin={{ top: 10, right: 25, left: -18, bottom: 20 }}><CartesianGrid stroke="#edf1f4"/><XAxis dataKey={xKey} type="number" name={xLabel} {...axis} label={{ value: xLabel, position: 'bottom', fontSize: 12, fill: '#7c8996' }}/><YAxis dataKey="health_score" name="Health" domain={[0, 100]} {...axis}/><Tooltip {...tip} cursor={{ strokeDasharray: '3 3' }}/><Scatter data={data} fill="#209d8b"/></ScatterChart></ResponsiveContainer></div>; }
