import { Activity, ShieldAlert, TrendingDown, ArrowUpRight, Box, FileText, ArrowRight, Layers3 } from 'lucide-react';
import { useBridge } from '../store/bridgeStore';
import { num, color } from '../utils/format';
import { PageTitle, Metric, Panel, Badge, Source, LinkButton, HealthBar } from '../components/common/UI';
import BridgeScene from '../components/bridge/BridgeScene';
import Timeline from '../components/bridge/Timeline';
import { TrendChart } from '../components/charts/Charts';
export default function Dashboard() {
  const {state,navigate,select}=useBridge(); const s=state.summary;
  const attention=[...state.components].sort((a,b)=>a.health_score-b.health_score).slice(0,3);
  const future=state.predictions.map(p=>({year:Math.round(state.simulation.year)+p.horizon,health_score:p.health_score}));
  return <><PageTitle title="Your bridge, in perspective." description="Understand today's condition. Make informed decisions for tomorrow."><Source>{state.metadata.data_source}</Source><button className="btn" onClick={()=>navigate('reports')}><FileText size={16}/>Assessment report</button></PageTitle>
    <div className="metrics-row"><Metric label="Overall bridge health" value={num(s.health_score)} unit="/100" accent icon={Activity}><Badge risk={s.risk_level}/><span>Weighted condition score</span></Metric><Metric label="Components to prioritize" value={s.high_risk_count} unit={`/ ${s.component_count}`} icon={ShieldAlert} note="High risk or critical condition"/><Metric label="1-year estimated health" value={num(s.predicted_health_1y)} unit="/100" icon={TrendingDown} note={`${num(s.health_score-s.predicted_health_1y)} points below current state`}/><Metric label="5-year estimated health" value={num(s.predicted_health_5y)} unit="/100" icon={TrendingDown} note="No new maintenance · model forecast"/></div>
    <div className="overview-main"><div className="twin-panel"><div className="twin-panel-title"><div><Box size={18}/><h3>Bridge digital twin</h3><span className="subtle-pill">8 mapped components</span></div><LinkButton onClick={()=>navigate('twin')}>Open workspace</LinkButton></div><BridgeScene components={state.components} compact/><Timeline/></div>
      <Panel title="Attention required" eyebrow="MAINTENANCE PRIORITY" className="attention-panel" action={<span className="count-tag">{s.high_risk_count}</span>}><p className="muted small">Lowest-condition components in the active state.</p><div className="attention-list">{attention.map((c,i)=><button className="attention-item" key={c.component_id} onClick={()=>{select(c.component_id);navigate('twin');}}><span className="attention-number">0{i+1}</span><div><div><b>{c.name}</b><ArrowUpRight size={14}/></div><span>{c.component_id}</span><div className="attention-risk"><Badge risk={c.risk_level}/><strong>{num(c.health_score)}<small>/100</small></strong></div></div></button>)}</div><div className="priority-foot"><span>Recommended next step</span><b>{s.priority}</b><button className="btn primary" onClick={()=>navigate('maintenance')}>Plan maintenance<ArrowRight size={16}/></button></div></Panel>
    </div>
    <div className="dashboard-charts"><Panel title="Condition outlook" eyebrow="5-YEAR PROJECTION" action={<Source>PREDICTION</Source>}><div className="chart-caption"><span>Estimated health score / 100</span><b className="negative">−{num(s.health_score-s.predicted_health_5y)} pts over 5 years</b></div><TrendChart data={future} height={225}/></Panel><Panel title="Component condition" eyebrow="CURRENT STATE" action={<LinkButton onClick={()=>navigate('analytics')}>Analytics</LinkButton>}><div className="component-bars">{state.components.map(c=><HealthBar key={c.component_id} value={c.health_score} risk={c.risk_level} label={c.name} onClick={()=>{select(c.component_id);navigate('twin');}}/>)}</div></Panel></div>
    <div className="operation-strip"><div><span>TRAFFIC LOAD</span><b>{num(state.environment.traffic_load,0)}<small>%</small></b></div><div><span>HEAVY VEHICLES</span><b>{num(state.environment.heavy_vehicle_percentage,0)}<small>%</small></b></div><div><span>TEMPERATURE</span><b>{num(state.environment.temperature,0)}<small>°C</small></b></div><div><span>ENVIRONMENTAL EXPOSURE</span><b>{num(state.environment.environmental_exposure*100,0)}<small>/100</small></b></div><div><Source>{state.metadata.data_source}</Source><small>No physical sensor connection</small></div></div>
    {state.recent_activity.length>0 && <Panel title="Recent scenario activity" className="recent-panel">{state.recent_activity.slice(0,3).map(r=><div className="activity-row" key={r.id}><span className="activity-icon"><Layers3 size={16}/></span><b>{r.name}</b><span>{r.horizon}-year horizon</span><Source>SIMULATION</Source></div>)}</Panel>}
  </>;
}
