import { useEffect, Suspense, lazy, Component } from 'react';
import { CheckCircle2, LoaderCircle, RefreshCw } from 'lucide-react';
import { useBridge } from './store/bridgeStore';
import Layout from './components/layout/Layout';
import { ErrorNotice, Button } from './components/common/UI';
import { useWebTools } from './hooks/useWebTools';
const pages={overview:lazy(()=>import('./pages/Dashboard')),twin:lazy(()=>import('./pages/DigitalTwin')),analytics:lazy(()=>import('./pages/Analytics')),predictions:lazy(()=>import('./pages/Predictions')),simulation:lazy(()=>import('./pages/Simulation')),maintenance:lazy(()=>import('./pages/Maintenance')),data:lazy(()=>import('./pages/DataExplorer')),reports:lazy(()=>import('./pages/Reports'))};
class AppBoundary extends Component {state={error:null};static getDerivedStateFromError(error){return {error};}render(){return this.state.error?<div className="load-screen"><h1>This view could not load.</h1><p>Your backend state is preserved. Reload to reconnect.</p><button className="btn primary" onClick={()=>location.reload()}>Reload workspace</button></div>:this.props.children;}}
function Workspace(){const {state,page,loading,error,toast,load,playing,speed,tick,dismissError}=useBridge();useEffect(()=>{load();},[]);useEffect(()=>{if(!playing)return;let cancelled=false;let timer;const run=async()=>{await tick(speed);if(!cancelled&&useBridge.getState().playing)timer=setTimeout(run,1300);};timer=setTimeout(run,600);return()=>{cancelled=true;clearTimeout(timer);};},[playing,speed]);const Page=pages[page]||pages.overview;return <Layout>{error&&<ErrorNotice text={error} onClose={dismissError}/>}<div aria-live="polite" className="toast-region">{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>{loading?<div className="load-screen"><LoaderCircle size={30} className="spin"/><h2>Connecting the twin…</h2><p>Loading component state and model forecasts.</p></div>:!state?<div className="load-screen"><h2>Start your BridgeTwin backend</h2><p>The workspace needs the local API to load bridge state.</p><Button icon={RefreshCw} variant="primary" onClick={load}>Retry connection</Button></div>:<Suspense fallback={<div className="load-screen"><LoaderCircle className="spin"/>Loading workspace…</div>}><Page/></Suspense>}</Layout>;}
export default function App(){useWebTools();return <AppBoundary><Workspace/></AppBoundary>;}
